# Use the official Python 3.10.6 image
FROM python:3.10.6-slim

# Set the working directory in the container
WORKDIR /app

# Copy the local code to the container
COPY modules /app

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run your application
CMD ["python", "main.py"]
